### PR TITLE
mp_rational: initial implementation of the constructor from mpq_t.

### LINKED ISSUE #21: New functionality: Constructor for rational using mpq_srcptr

### PR DESCRIPTION
**Pull request by bluescarni**
@isuruf This fixes #21.

### CODE REVIEW

**Comment by isuruf** [comment]
Thanks. One comment, GMP always canonicalise its arguments. Canonicalise is not called only when you manipulate the numerator or denominator separately. So, I think `is_canonical` is not really necessary

**Comment by bluescarni** [comment]
@isuruf I was thinking of a use case in which you would use a non-canonicalised ``mpq_t`` for construction, but if you say it's not a realistic/useful scenario I'll be happy to remove it.

**Comment by bluescarni** [comment]
@isuruf Just to be clear, would you prefer the constructor to always canonicalise or never canonicalise?

**Comment by isuruf** [comment]
I prefer never canonicalise.
`mpq_t`'s are always canonicalised except at `mpq_set_ui` functions and function that manipulate numerator and denominator separately. User is expected to do canonicalisation before passing the `mpq_t` instances to other functions

**Comment by bluescarni** [comment]
@isuruf ok I implemented the change.

**Comment by isuruf** [comment]
+1

**Pull request merged**
