### PR TITLE
Added gitignore

### PR DESCRIPTION
**Pull request by Sumith1896**
@bluescarni

### CODE REVIEW

**Comment by Sumith1896** [comment]
Let me know if this is needed or not. I have no much idea of future Piranha. I thought if you plan to have many contributors this might be useful. 
Ping @bluescarni

**Comment by bluescarni** [comment]
@Sumith1896 Yes, thanks this is certainly useful! I usually add ignores in my local git config, but of course this is a much better solution.

I am wondering though why you are filtering out contents of ``tests``? This refers to the source of the tests right? Nothing should be created in there during builds.

**Comment by Sumith1896** [comment]
@bluescarni They are the executables of tests. Not needed in the repo, and are created during builds.

**Comment by Sumith1896** [comment]
@bluescarni Let me know if I have not made myself clear.
Whenever I build, I get the executables.

**Comment by bluescarni** [comment]
@Sumith1896 are you doing in-source builds or out-of-source builds?

**Comment by Sumith1896** [comment]
@bluescarni  I do in-source and the executables are generated along the source.
That's how some developers do it(also us in SymEngine).
Have a look at SymEngine's [gitignore](https://github.com/sympy/symengine/blob/bbe3c9baf653d18d37e3bfcd424e0781786098c1/.gitignore#L36).

**Comment by bluescarni** [comment]
Ah ok, cheers, that explains it. I use out-of-source builds myself, as explained in the docs:

http://bluescarni.github.io/piranha/getting_started.html

I am inclined to keep out-of-source the mandatory build procedure for now. If it is ok with you, I'll merge the PR and then modify the ``.gitignore`` later.

Thanks again!

**Comment by Sumith1896** [comment]
Cool, I'm personally have not build `Piranha` this way. Will look into it if that is the suggested practice.

Cheers

**Comment by bluescarni** [comment]
I like out-of-source builds for a variety of reasons. For instance, if I need to start over with a build, I can just remove the ``build`` directory and I will be certain that any temporary file generated in the build process is gone.

Another advantage is that it is easier to work with different compilers and compiler versions. Right now in my piranha local source tree I have the following build dirs: ``build``, ``build_check``, ``build_clang``, ``build_gcc_48``, ``build_gcc_51``, ``build_intel``, ``build_perf``, ``build_pyranha``, ``build_python_3`` :)

**Comment by Sumith1896** [comment]
The different compilers sounds interesting, even I should start using it.

For the first reason, you can always `git clean -dfx` if you have a `gitignore`.

**Comment by Sumith1896** [comment]
ping @bluescarni

**Comment by bluescarni** [comment]
@Sumith1896 Yep I have not forgotten about the PR :) I will get back to steady development after xmas holidays, but the PR is good to go. I will make a couple of minor modifications reflecting that the suggested way of compiling piranha is with out-of-tree builds, so I will exclude all ``build*`` directory and remove from the gitignore the files that might be generated by an in-tree build.

**Comment by bluescarni** [comment]
@Sumith1896 Merged, thanks!

**Comment by Sumith1896** [comment]
Thanks for the merge @bluescarni :)

**Pull request merged**
